apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-deployment
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      containers:
        - name: taskmanager
          image: {{.Values.image}}
          imagePullPolicy: Never
          ports:
            - containerPort: {{.Values.containerPort}}
          envFrom:
            - configMapRef:
                name: taskmanager-config
            - configMapRef:
                name: mysql-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"