apiVersion: v1
kind: Service
metadata:
  name: taskmanager-service
spec:
  type: NodePort
  selector:
    app: taskmanager
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080