apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  DB_HOST: mysql-headless
  DB_USER: root
  DB_NAME: "{{.Values.config.DB_NAME}}"
  DB_PORT: "{{.Values.config.DB_PORT}}"
  DB_DIALECT: mysql